// components
import { Rubik } from "next/font/google";
import Navbar from "./components/Navbar";

// types
import type { Metadata } from "next";

// styles
import "./globals.css";

// instantiate the font
const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Dojo Helpdesk"
};

type RootLayoutProps = {
  children: React.ReactNode;
};

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Navbar />

        {children}
      </body>
    </html>
  );
};

export default RootLayout;
