// components
import Navbar from "./components/Navbar";

// types
import type { Metadata } from "next";

// styles
import "./globals.css";

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App"
};

type RootLayoutProps = {
  children: React.ReactNode;
};

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body>
        <Navbar />

        {children}
      </body>
    </html>
  );
};

export default RootLayout;
